### ISSUE TITLE
Invalid coloring of /yourbids.php

### ISSUE THREAD

**Issue by Komosa** [renlok/WeBid#169]
When two users sets same bid value (eg 1100) then given auction isn't yellow on both users yourbids screen.

Only one has green "You are the current highest bidder" message on item page although.

**Comment by renlok** [comment]
Is this a current issue (with the git version) I remember seeing another issue like ths in the past but I thought it had been fixed in the repo

**Comment by Komosa** [comment]
If this was question, I'm was using `WeBid-1.1.2P2` downloaded from webidsupport.com

**Comment by Nozlaf** [comment]
probably best to post that to the forums at webidsupport.com as the issue doesn't exist in the unstable development version hosted here someone should be able to provide a fix there quickly

**Comment by nay27uk** [comment]
This is still a problem in the git please see my forum post here in the RC testing thread here.

http://www.webidsupport.com/forums/index.php?threads/1-2-rc4.8011/page-13#post-48989

**Comment by aucsta** [comment]
Can this now be closed
